openapi: 3.0.0
info:
  title: API do Assessor de Investimentos Virtual
  description: API REST para cadastro de clientes, definição de perfil de investidor e recomendação de carteiras de investimento.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Servidor de Desenvolvimento Local

tags:
  - name: Clientes
    description: Operações relacionadas ao ciclo de vida dos clientes e suas recomendações.
  - name: Produtos de Investimento
    description: Gerenciamento do catálogo de produtos de investimento disponíveis.

paths:
  # Rotas de Clientes
  /clientes:
    post:
      tags: [Clientes]
      summary: Cria um novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
      responses:
        '201':
          description: Cliente criado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
        '400':
          description: Dados inválidos ou e-mail já cadastrado.
    get:
      tags: [Clientes]
      summary: Lista todos os clientes cadastrados
      responses:
        '200':
          description: Lista de clientes retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClienteResponse'

  /clientes/{id}:
    get:
      tags: [Clientes]
      summary: Busca um cliente pelo seu ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Cliente encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
        '404':
          description: Cliente não encontrado.
    put:
      tags: [Clientes]
      summary: Atualiza os dados de um cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
      responses:
        '200':
          description: Cliente atualizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
        '404':
          description: Cliente não encontrado.
    delete:
      tags: [Clientes]
      summary: Deleta um cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Cliente deletado com sucesso.
        '404':
          description: Cliente não encontrado.

  /clientes/{id}/perfil:
    post:
      tags: [Clientes]
      summary: Define o perfil de investidor de um cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerfilRequest'
      responses:
        '200':
          description: Perfil definido com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerfilResponse'
        '404':
          description: Cliente não encontrado.

  /clientes/{id}/recomendacoes:
    get:
      tags: [Clientes]
      summary: Obtém a carteira de investimentos recomendada para um cliente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Recomendação gerada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecomendacaoResponse'
        '404':
          description: Cliente ou perfil não encontrado.

  # Rotas de Produtos de Investimento
  /investimentos:
    post:
      tags: [Produtos de Investimento]
      summary: Cria um novo produto de investimento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoInvestimentoRequest'
      responses:
        '201':
          description: Produto criado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoInvestimento'
    get:
      tags: [Produtos de Investimento]
      summary: Lista todos os produtos de investimento
      responses:
        '200':
          description: Lista de produtos retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProdutoInvestimento'

  /investimentos/{id}:
    get:
      tags: [Produtos de Investimento]
      summary: Busca um produto de investimento pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoInvestimento'
        '404':
          description: Produto não encontrado.
    put:
      tags: [Produtos de Investimento]
      summary: Atualiza um produto de investimento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoInvestimentoRequest'
      responses:
        '200':
          description: Produto atualizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoInvestimento'
        '404':
          description: Produto não encontrado.
    delete:
      tags: [Produtos de Investimento]
      summary: Deleta um produto de investimento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Produto deletado com sucesso.
        '404':
          description: Produto não encontrado.

components:
  schemas:
    ClienteRequest:
      type: object
      properties:
        nome:
          type: string
          example: "Maria da Silva"
        email:
          type: string
          example: "maria.silva@email.com"
      required: [nome, email]
    ClienteResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: "Maria da Silva"
        email:
          type: string
          example: "maria.silva@email.com"
        perfilId:
          type: integer
          nullable: true
          example: 2
    PerfilRequest:
      type: object
      properties:
        respostas:
          type: object
          description: As respostas para as perguntas do questionário.
          properties:
            toleranciaRisco:
              type: string
              enum: [A, B, C]
              example: "B"
            objetivo:
              type: string
              enum: [A, B, C]
              example: "C"
            conhecimento:
              type: string
              enum: [A, B, C]
              example: "A"
    PerfilResponse:
      type: object
      properties:
        id:
          type: integer
          example: 2
        nome:
          type: string
          example: "Moderado"
        descricao:
          type: string
          example: "Busca um equilíbrio entre segurança e rentabilidade."
    ProdutoInvestimento:
      type: object
      properties:
        id:
          type: integer
          example: 3
        nome:
          type: string
          example: "Fundo Imobiliário HGLG11"
        tipo:
          type: string
          example: "FII"
        risco:
          type: string
          enum: [Baixo, Médio, Alto]
          example: "Médio"
    ProdutoInvestimentoRequest:
      type: object
      properties:
        nome:
          type: string
          example: "Tesouro IPCA+ 2045"
        tipo:
          type: string
          example: "Renda Fixa"
        risco:
          type: string
          enum: [Baixo, Médio, Alto]
          example: "Médio"
      required: [nome, tipo, risco]
    ProdutoRecomendado:
      type: object
      properties:
        nome:
          type: string
          example: "Tesouro Selic"
        tipo:
          type: string
          example: "Renda Fixa"
        risco:
          type: string
          example: "Baixo"
        percentualAlocacao:
          type: integer
          example: 40
    RecomendacaoResponse:
      type: object
      properties:
        perfilInvestidor:
          type: string
          example: "Moderado"
        descricaoPerfil:
          type: string
          example: "Busca um equilíbrio entre segurança e rentabilidade."
        carteiraRecomendada:
          type: array
          items:
            $ref: '#/components/schemas/ProdutoRecomendado'
